---
dist: xenial
services:
  - xvfb
addons:
  firefox: "67.0.1"
before_install:
  - sudo apt-get update
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz
  - sudo cp geckodriver /usr/bin
install:
  - "pip install pytest pylint pycodestyle pydocstyle selenium kivy "
language: python
python:
  - "3.7"
script:
  - pytest test_code.py
  - pylint application.py
  - pycodestyle application.py
  - pydocstyle application.py
  - xvfb-run --server-args="-screen 0 1024x768x24" make test
notifications:
  email:
    recipients:
      - user@example.com
    on_success: always
on_failure: always