---
dist: xenial
before_script:
- wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
- export CHROME_BIN=chromium-browser
install:
  - "pip install pytest pylint pycodestyle pydocstyle selenium kivy"
language: python
python:
  - "3.7"
script:
  - pytest test_code.py
  - pylint application.py, scraper.py
  - pycodestyle application.py, scraper.py
  - pydocstyle application.py, scraper.py
notifications:
  email:
    recipients:
      - user@example.com
    on_success: always
on_failure: always


