---
os: windows
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - export KIVY_GL_BACKEND=mock
  - sudo apt-get install python-pip build-essential git python-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
install:
  - "pip install pytest pylint pycodestyle pydocstyle selenium kivy"
language: python
python:
  - "3.7"
script:
  - pytest test_code.py
  - pylint application.py, scraper.py
  - pycodestyle application.py, scraper.py
  - pydocstyle application.py, scraper.py
notifications:
  email:
    recipients:
      - user@example.com
    on_success: always
on_failure: always


