---
dist: xenial
install:
  - "pip install pytest pylint pycodestyle pydocstyle selenium kivy chromedriver-binary"
language: python
python:
  - "3.7"
script:
  - pytest test_code.py
  - pylint application.py
  - pycodestyle application.py
  - pydocstyle application.py
notifications:
  email:
    recipients:
      - user@example.com
    on_success: always
on_failure: always