---
dist: xenial
install:
  - "pip install pytest pylint pycodestyle pydocstyle selenium kivy chromedriver-binary"
language: python
python:
  - "3.7"
script:
  - pylint part_1.py
  - pycodestyle part_1.py
  - pydocstyle part_1.py
notifications:
  email:
    recipients:
      - user@example.com
    on_success: always
on_failure: always